enum Role {
  user
  admin
}

type User {
  id: ID!
  email: String!
  createdAt: DateTime!
  votes: [VOTED_BY!]!
}

extend type Query {
  Login (email: String!, password: String!): String!
  currentUser (name: String): String
  users: [User!] @hasRole (roles: [admin])
    @cypher(
      statement: "MATCH (u:User) WITH { username: u.username, id: u.id, email: u.email} as User RETURN User"
    )
}

extend type Mutation {
  Signup (email: String!, password: String!): String!
  UpdatePassword (email: String!, password: String!, _new: String!): String!
}
