type Topic {
  # id: ID!
  name: String!
  children: [IS_PART_OF!]!
  parents: [IS_PART_OF!]!
}

type IS_PART_OF @relation (name: "IS_PART_OF") {
  from: Topic!
  to: Topic!
}

input CreateTopicInput {
  name: String!
  children: [String!]!
  parents: [String!]!
}

extend type Mutation {
  # createTopic (input: CreateTopicInput!): Topic! @hasRole (roles: [admin])
  createTopic (name: String!, children: [String!]!, parents: [String!]!): User! @hasRole (roles: [admin])
}